
services:
  backend:
    build: ./backend
##    container_name: backend
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db

  proxy:
    image: httpd:2.4
##    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/reverse-proxy.conf:/usr/local/apache2/conf/extra/reverse-proxy.conf:ro
      - ./apache/ssl.conf:/usr/local/apache2/conf/extra/ssl.conf:ro
      - ./apache/server.crt:/usr/local/apache2/conf/server.crt:ro
      - ./apache/server.key:/usr/local/apache2/conf/server.key:ro
    command: >
      sh -c "echo 'LoadModule proxy_module modules/mod_proxy.so' >> /usr/local/apache2/conf/httpd.conf &&
            echo 'LoadModule proxy_http_module modules/mod_proxy_http.so' >> /usr/local/apache2/conf/httpd.conf &&
            echo 'Include /usr/local/apache2/conf/extra/reverse-proxy.conf' >> /usr/local/apache2/conf/httpd.conf &&
            httpd-foreground"
    depends_on:
      - backend

  db:
    image: postgres:15
##    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  jenkins:
    build: ./jenkins
##    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      - Lang=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8

volumes:
  postgres_data:
  jenkins_home: