LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ServerName localhost

<VirtualHost *:80>
    ProxyPreserveHost On


    ProxyPass / http://backend:5000/
    ProxyPassReverse / http://backend:5000/
</VirtualHost>

Include /usr/local/apache2/conf/extra/ssl.conf